#!/usr/bin/env bash
# -----------------------------------------------------------------------------------------------
# Human baseline step 1: generate the Spring Boot starter with Spring Initializr and merge it into
# this repository WITHOUT overwriting existing files (specs, frozen tests, seed SQL...).
# The AI never generates the project skeleton or the build file.
#
# Usage: scripts/bootstrap.sh
# -----------------------------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."

GROUP_ID="com.seniorglez"
ARTIFACT_ID="prices"            # the name "prices" makes Initializr generate PricesApplication
PACKAGE_NAME="com.seniorglez.prices"
JAVA_VERSION="21"
DEPENDENCIES="web,data-jpa,h2,validation"
INITIALIZR_URL="https://start.spring.io/starter.zip"

for tool in curl unzip git java; do
  command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 1. Starter ----------------------------------------------------------------------------------------
if [[ -f pom.xml ]]; then
  echo "pom.xml already exists: skipping the Initializr download."
else
  echo "Downloading starter from $INITIALIZR_URL ..."
  curl -fsSL "$INITIALIZR_URL" \
    -d type=maven-project \
    -d language=java \
    -d javaVersion="$JAVA_VERSION" \
    -d groupId="$GROUP_ID" \
    -d artifactId="$ARTIFACT_ID" \
    -d name="$ARTIFACT_ID" \
    -d packageName="$PACKAGE_NAME" \
    -d dependencies="$DEPENDENCIES" \
    -o "$TMP/starter.zip"

  unzip -q "$TMP/starter.zip" -d "$TMP/starter"
  SRC="$TMP/starter"
  [[ -f "$SRC/$ARTIFACT_ID/pom.xml" ]] && SRC="$SRC/$ARTIFACT_ID"

  echo "Merging starter files (existing files are kept):"
  (cd "$SRC" && find . -type f | sort) | while read -r file; do
    if [[ -e "$file" ]]; then
      echo "  kept     $file"
    else
      mkdir -p "$(dirname "$file")"
      cp "$SRC/$file" "$file"
      echo "  added    $file"
    fi
  done
  chmod +x mvnw

  BOOT_VERSION="$(sed -n '/<parent>/,/<\/parent>/p' pom.xml | sed -n 's:.*<version>\(.*\)</version>.*:\1:p' | head -n 1)"
  cat > baseline/STARTER.md <<INFO
# Starter provenance

Generated by \`scripts/bootstrap.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

| Setting | Value |
|---|---|
| Spring Boot | ${BOOT_VERSION:-unknown} |
| Java | $JAVA_VERSION |
| Build | Maven (wrapper included) |
| Group / artifact | $GROUP_ID / $ARTIFACT_ID |
| Package | $PACKAGE_NAME |
| Dependencies | $DEPENDENCIES |
| Source | $INITIALIZR_URL |

Added by hand afterwards (see \`baseline/pom-*.xml\`): ArchUnit (test), JaCoCo coverage check.
INFO
  echo "Recorded starter provenance in baseline/STARTER.md (Spring Boot ${BOOT_VERSION:-unknown})."
fi

# 2. pom.xml additions (idempotent) ------------------------------------------------------------------
insert_before_first() {   # $1 = closing tag, $2 = snippet file
  awk -v tag="$1" -v snippet="$2" '
    index($0, tag) && !done { while ((getline line < snippet) > 0) print line; close(snippet); done = 1 }
    { print }
  ' pom.xml > "$TMP/pom.xml" && mv "$TMP/pom.xml" pom.xml
}

if grep -q "<artifactId>archunit</artifactId>" pom.xml; then
  echo "pom.xml already contains the baseline additions."
else
  insert_before_first "</dependencies>" baseline/pom-dependencies.xml
  if ! grep -q "<artifactId>spring-boot-starter-test</artifactId>" pom.xml; then
    insert_before_first "</dependencies>" baseline/pom-starter-test.xml
  fi
  insert_before_first "</plugins>" baseline/pom-plugins.xml
  echo "Added ArchUnit and the JaCoCo check to pom.xml."
fi

# 3. Git hygiene -------------------------------------------------------------------------------------
touch .gitignore
grep -qxF ".claude/settings.local.json" .gitignore || printf '\n# Claude Code personal settings\n.claude/settings.local.json\n' >> .gitignore
chmod +x .claude/hooks/verify-gate.sh

cat <<'NEXT'

Next steps (human):
  1. ./mvnw -q test-compile      # must succeed: the frozen tests compile without production code
  2. ./mvnw test                  # expected RED: acceptance tests (404 on /prices) and architecture tests (empty layers)
  3. Review specs/ (decisions D-01 and D-02), then freeze the baseline:
       git add -A
       git commit -m "chore: human baseline (specs, frozen tests, seed data, starter)"
       git tag baseline
  4. Start Claude Code in the repository root and run /implement-all (or /next-task repeatedly).
NEXT
